### ISSUE TITLE
Meta: daroczig.github.io/dbr 404

### ISSUE THREAD

**Issue by grahamperrin** [daroczig/dbr#9]
https://daroczig.github.io/slides/2020-01-29_rstudio-conf_getting-things-logged/#/9 refers to: 

* https://daroczig.github.io/dbr

– that's 404, not found

**Comment by daroczig** [comment]
Oh, wow -- I'm so sorry, just saw your comment here :facepalm: 
Let me fix that and get back to you later today.

**Comment by daroczig** [comment]
https://daroczig.github.io/dbr is now live, thanks again for the report
